# Datasource
spring:
  datasource:
    generate-unique-name: false
    name: test
    username: sa
    password:
  h2:
    console:
      path: /h2-console

# Logging of SQL queries
logging:
  level:
    sql: debug

# Application configuration properties
shaurma:
  orders:
    pageSize: 10
