# Datasource
spring:
  datasource:
    generate-unique-name: false
    name: test
    username: sa
    password:
  h2:
    console:
      path: /h2-console
  profiles:
#    active: in-memory-user-details
    active: data-jpa-user-details

# Logging of SQL queries
logging:
  level:
    sql: debug
